### ISSUE TITLE
[QnA] 스터디 사후 분석

### ISSUE THREAD

**Issue by madplay** [NMP-Study/spark2023#14]

**Comment by madplay** [comment]
### Q) DAG, MapReduce 등등은 일단 스킵하고 넘어가도 되는가?
### Q) 스파크 세션이라는 것은 ?
### Q) 클러스터는 애플리케이션의 묶음이라고 말할 수 있는가?
### Q) 분산 데이터... 사내에도 동일한가요?
### Q) 파퀘이가 뭐에요?

**Comment by bluewbear** [comment]
- [What happens if SparkSession is not closed?](https://stackoverflow.com/questions/44058122/what-happens-if-sparksession-is-not-closed)
  - 질문을 올린게 좀 시간이 흘렀지만, [close](url)가 있는 건 다 이유가 있을 것으로 보임 ㅎ
  - [pyspark.sql.SparkSession.stop](https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.SparkSession.stop.html)
  - 심지어 version 2.0에 추가된..? 1.0도 아니고?
